version: "3"
services:
  db:
    container_name: electric_miles_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "13306:3306"

  app_build:
    container_name: electric_miles_app_build
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    command: sh -c "composer dump-autoload && composer install --no-interaction"
    depends_on:
      - db

  app:
    container_name: electric_miles_app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    volumes:
      - ./:/app
      - ./docker/nginx/10-php.conf:/opt/docker/etc/nginx/vhost.common.d/10-php.conf
    ports:
      - "5000:80"
    depends_on:
      - app_build
